use_frameworks!

target 'ZZRefreshSwifty_Example' do
  pod 'ZZRefreshSwifty', :path => '../'
  pod 'SnapKit', '~> 3.2.0'
  target 'ZZRefreshSwifty_Tests' do
    inherit! :search_paths

    
  end
end
